In [1]:
%load_ext autoreload

In [2]:
import pandas as pd
import seaborn as sns
import numpy as np

In [3]:
!conda env list

# conda environments:
#
# * -> active
# + -> frozen
                         /Users/yugant/Data Science/Code/h501-gutenberg/.conda
base                     /Users/yugant/miniconda3
h501-gutenberg       *   /Users/yugant/miniconda3/envs/h501-gutenberg
student-performance      /Users/yugant/miniconda3/envs/student-performance
week-5-titanic           /Users/yugant/miniconda3/envs/week-5-titanic
week0-webapp             /Users/yugant/miniconda3/envs/week0-webapp

In [4]:
authors = pd.read_csv(
    "https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-06-03/gutenberg_authors.csv"
)

authors.head()

authors.columns

Index(['gutenberg_author_id', 'author', 'alias', 'birthdate', 'deathdate',
       'wikipedia', 'aliases'],
      dtype='str')

In [5]:
meta = pd.read_csv(
    "https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-06-03/gutenberg_metadata.csv")

meta.head()

#meta.columns

,gutenberg_id,title,author,gutenberg_author_id,language,gutenberg_bookshelf,rights,has_text
0,1,The Declaration of Independence of the United ...,"Jefferson, Thomas",1638.0,en,Politics/American Revolutionary War/United Sta...,Public domain in the USA.,True
1,2,The United States Bill of Rights\r\nThe Ten Or...,United States,1.0,en,Politics/American Revolutionary War/United Sta...,Public domain in the USA.,True
2,3,John F. Kennedy's Inaugural Address,"Kennedy, John F. (John Fitzgerald)",1666.0,en,Browsing: History - American/Browsing: Politics,Public domain in the USA.,True
3,4,Lincoln's Gettysburg Address\r\nGiven November...,"Lincoln, Abraham",3.0,en,US Civil War/Browsing: History - American/Brow...,Public domain in the USA.,True
4,5,The United States Constitution,United States,1.0,en,United States/Politics/American Revolutionary ...,Public domain in the USA.,True

In [6]:
df = pd.merge(
    authors,
    meta,
    on="gutenberg_author_id",
    how="inner"
)

df.head()

,gutenberg_author_id,author_x,alias,birthdate,deathdate,wikipedia,aliases,gutenberg_id,title,author_y,language,gutenberg_bookshelf,rights,has_text
0,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,2,The United States Bill of Rights\r\nThe Ten Or...,United States,en,Politics/American Revolutionary War/United Sta...,Public domain in the USA.,True
1,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,5,The United States Constitution,United States,en,United States/Politics/American Revolutionary ...,Public domain in the USA.,True
2,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,116,Motion Pictures of the Apollo 11 Lunar Landing,United States,en,Browsing: Computers & Technology/Browsing: Eng...,Public domain in the USA.,True
3,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,239,Radar Map of the United States,United States,en,Browsing: Travel & Geography,Public domain in the USA.,True
4,1,United States,U.S.A.,NaN,NaN,https://en.wikipedia.org/wiki/United_States,U.S.A.,251,1995 United States Congressional Address Book,United States,en,Browsing: History - American/Browsing: Politics,Public domain in the USA.,True

In [7]:
from gutenberg.authors import *

list_authors(by_languages=True, alias=True)

['Wells, Herbert George',
 'Chaney, John Griffith',
 'Stevenson, R. L. (Robert Louis)',
 'Jacobs, William Wymark',
 'Ballantyne, Robert Michael',
 'De Maupassant, Guy',
 'Lang, Walter Andrew',
 'Πλάτων',
 'Wangemann, Eduard Carl Otto',
 'Barbour, R. H. (Ralph Henry)',
 "Wilde, Oscar Fingal O'Flahertie Wills",
 'Harte, Francis Bret',
 'Sinjohn, John',
 'Alighieri, Dante',
 'Ruskin, J. (John)',
 'Houghton, Carolyn Wells',
 'Strindberg, Johan August',
 'Carter, Nick',
 'Huxley, T. H. (Thomas Henry)',
 'Gloux, Olivier',
 'Crawford, Francis Marion',
 'Collins, William Wilkie',
 'Rollan, R.',
 'James, George Payne Rainsford',
 'Darwin, Charles Robert',
 'Poe, Edgar Allen',
 'Chambers, Robert William',
 'Burgess, Thornton Waldo',
 'Richards, Laura E.',
 'Borrow, George Henry',
 'Daudet, Louis Marie Alphonse',
 'Snell, Roy Judson',
 'Michelet, J.',
 'Yeats, William Butler',
 'Swift, J. (Jonathan)',
 'Russell, W. Clark (William Clark)',
 'Carlyle, T. (Thomas)',
 'Curwood, James-Oliver',
 'Hawkins, Anthony Hope',
 'Hancock, Harrie Irving',
 'Becke, George Louis',
 'Crayon, Geoffrey',
 'Harper, C. G.',
 'Όμηρος',
 "O'Hara, Kenneth",
 'Kataja, Vaino',
 'Weyman, Stanley J. (Stanley John)',
 'Dodgson, Charles Lutwidge',
 'Andersen, Hans Christian',
 'Wallace, Richard Horatio Edgar',
 'Lancaster, William Joseph Cosens',
 'Administration, Work Projects',
 'Mikkola, Maila Winter',
 'Brehm, A. E. (Alfred Edmund)',
 'Gaboriau, Émile',
 'Allen, Charles Grant Blairfindie',
 'Fletcher, Joseph Smith',
 'Holmes, Gordon',
 'Sabatini, R.',
 'Sterling, Brett',
 'Williamson, Charles Norris',
 'Cobb, Irvin Shrewsbury',
 'Leiber, Fritz Reuter',
 'Morley, Viscount',
 'Hall, Eugene Raymond',
 "Vandercook, Margaret O'Bannon Womack",
 'Barrili, Antonio Giulio',
 'Wheeler, Ella',
 'Smith, F. Hopkinson (Francis Hopkinson)',
 'Grile, Dod',
 'Farjeon, Benjamin Leopold',
 'Howard, Robert Ervin',
 'C.L.S.C.',
 'Guerrazzi, F. D. (Francesco Domenico)',
 'Jarvis, E. K.',
 'Morris, William M.',
 'Couperus, Louis Marie Anne',
 'Weymouth, R. F. (Richard Francis)',
 'Stevenson, Burton E.',
 'Barr, Amelia Edith Huddleston',
 'Lessing, G. E.',
 'Melville, Hermann',
 'Raine, William McLeod',
 'Paivarinta, Pietari',
 'Grimm, Wilhelm Carl',
 'Grimm, Jacob Ludwig Carl',
 'Blackmore, Richard Doddridge',
 'Clarke, Rebecca Sophia',
 'Coleridge, S. T. (Samuel Taylor)',
 'Stooke, E. H.',
 'Fontenay, Charles Louis',
 'Pimentel, Alberto Augusto de Almeida',
 'Storm, Hans Theodor Woldsen',
 'Gissing, George Robert',
 'Marks, Winston Kinney',
 'Raymond, Evelyn Hunt',
 'Wilkuna, Kyosti',
 'Beamont, Francis',
 'Korhonen, Veikko Matias',
 'Mason, Alfred Edward Woodley',
 'Malot, Hector-Henri',
 'Kock, Charles Paul de',
 'Eotvos, Karoly',
 'Graham, John',
 'Wassermann, Jacob',
 'Sinclair, Mary Amelia St. Clair',
 'Cantu, Cesare',
 'Porter, William Sidney',
 'Roy, Lillian Elizabeth Becker',
 'Tennyson, Alfred Lord',
 'Herford, O. (Oliver)',
 'Longfellow, Henry W.',
 'Harmon, James Judson',
 'Roberts, Brigham Henry',
 'Home, Gordon Cochrane',
 'Cawein, Madison J.',
 'Thoreau, Henry D. (Henry David)',
 'Wade, Mary Hazleton',
 'Lie, Jonas Lauritz Idemil',
 'Griffiths, Arthur George Frederick',
 'Burghard, Sidney Groves',
 'Douglas, Amanda Minnie',
 'Crockett, Samuel Rutherford',
 'Brereton, Frederick Sadleir',
 'McLaren, Alexander',
 'Steel, F. A. (Flora Annie)',
 'Jefferies, John Richard',
 'Lincoln, Joseph C.',
 'Speight, Thomas Wilkinson',
 'Beach, Rex Ellingwood',
 'United States President (1801-1809)',
 'Walpole, Sir Hugh',
 'Bunyan, Johann',
 'Sabin, Edwin Legrand',
 'Roe, E. P. (Edward Payson)',
 'Glyn, Elinor Sutherland',
 'Disraeli, B. (Benjamin), Earl of Beaconsfield',
 'Snaith, John Collis',
 'Bacheller, Addison Irving',
 'Ambrus, Zoltan',
 'Smith, Johnston',
 'Merimee, Prosper',
 'Guthrie, Thomas Anstey',
 'Mitton, Geraldine Edith',
 'Aldrich, T. B. (Thomas Bailey)',
 'Ward, Arthur Sarsfield',
 'Cabell, Branch',
 'Cellarius',
 'Wuori, M.',
 'Tweedsmuir, John Buchan, Baron',
 'Young, Robert Franklin',
 'Biro, Lajos',
 'Hackluyt, Richard',
 'Haeckel, Ernst Heinrich Philipp August',
 'Morley, Christopher Darlington',
 'Hewlett, Maurice Henry',
 'Mill, J. S. (John Stuart)',
 'James, Florence Alice Price',
 'Reeve, Arthur Benjamin',
 'Ellis, Henry Havelock',
 'Erasmus, of Rotterdam',
 'Woolsey, Sarah Chauncey',
 'Watson, John',
 'Lonnrot, Elias',
 'Gallun, Raymond Zinke',
 'Boothby, Guy Newell',
 'Symonds, J. A. (John Addington)',
 'Saunders, Margaret Marshall',
 'Leacock, Stephen Butler',
 'Heine, H. (Heinrich)',
 'Fabian, Warner',
 'Quin, Dan',
 'Sharkey, John Michael',
 'Bang, Herman Joachim',
 'Shelley, P. B. (Percy Bysshe)',
 'Hutcheson, John Conroy',
 'McIntyre, John Thomas',
 'Cory, David Magie',
 'Effendi, Shoghi',
 'Gull, Cyril Arthur Edward Ranger',
 'Fewkes, J. Walter (Jesse Walter)',
 'Parkman, F. (Francis)',
 'Runeberg, J. L. (Johan Ludvig)',
 'Zangwill, I. (Israel)',
 'Browne, Thomas Alexander',
 'Whitman, Walter',
 'Ingraham, Colonel Prentiss',
 'Paget, Violet',
 'Válmíki',
 'Long, William Joseph',
 'Baruch, Moses',
 'Smith, Grace',
 'Kafka, F. (Franz)',
 'Hasse, Henry Louis',
 'Burgess, Frank Gelett',
 'Neville, Kris Ottman',
 'Gordon, Charles William',
 'Stoker, Abraham',
 'Schmitz, James Henry',
 'Tranquillus, Gaius Suetonius',
 'Porter, Eleanor Hodgman',
 'Saintsbury, George Edward Bateman',
 'Gregg, Hilda Caroline',
 'Siebe, Josefine',
 'Patchin, Frank Glines',
 'Saltus, Edgar Evertson',
 '羅貫中',
 'Abdul-Baha',
 'Huxley, Aldous Leonard',
 'Duellman, William E. (William Edward)',
 'Stanhope, Philip Dormer, Earl of Chesterfield',
 'Forster, Edward Morgan',
 'Smith, Sarah',
 'March, Anne',
 'Bazin, Rene',
 'Green, Olive',
 'Pyle, Katherine',
 'Huneker, James Gibbons',
 'Gibbs, George Fort',
 'Carey, R. Nouchette (Rosa Nouchette)',
 'Gutenberg, Project',
 'Banzole, Ottone di',
 'Hegel, G. W. F. (Georg Wilhelm Friedrich)',
 'Barrett-Browning, Elizabeth',
 'Herrick, Robert Welch',
 'Bickerstaff, Isaac',
 'Kelland, Clarence B.',
 'Kivinen, Ilmari',
 'Diderot, Pantophile',
 'Bush, W. (Wilhelm)',
 'Moricz, Zsigmond',
 'Janvier, Thomas Allibone',
 'Maspero, Gaston Camille Charles, Sir',
 'Engels, Frederick',
 'Bloundelle-Burton, J. (John)',
 'Martin, Violet Florence',
 'Steiner, Rudolph',
 'Coburn, Fordyce, Mrs.',
 'Cable, G. W. (George Washington)',
 'Sydney, Margaret',
 'Deeping, George Warwick',
 'Gribbon, William Lancaster',
 'Luska, Sidney',
 'Riis, Jacob August',
 'Harben, William Nathaniel',
 'Tarbell, Ida Minerva',
 'Paine, Ralph D. (Ralph Delahaye)',
 'Fitch, Lucy',
 'Mangasarian, Mangasar Mugurditch',
 'Hurll, Estelle May',
 'Bernard, Paul',
 'Dick, Philip Kindred',
 'Jones, Raymond F. (Raymond Fisher)',
 'Abernathy, Robert Harwood',
 'Hauptmann, Gerhart Johann Robert',
 'Christie, Agatha Mary Clarissa Miller',
 'Serviss, Garrett P. (Garrett Putman)',
 'Lang, Allen K.',
 'Souvestre, Emile',
 'Cox, Irving England, Jr.',
 'Verhaeren, Émile',
 'Goldsmit, Oliver',
 'James, G. Wharton (George Wharton)',
 'King, William Benjamin Basil',
 'Wood, William Charles Henry',
 'Bullen, Frank T. (Frank Thomas)',
 'Norris, Benjamin Franklin',
 'Ohnet, Jorge',
 'Spence, James Lewis Thomas Chalmers',
 'Mitford, Miss',
 'Chaucer, Jeffrey',
 'Freeman, Richard Austin',
 'Kyne, Peter Bernard',
 'Pemberton, Sir Max',
 'Bensusan, Samuel Levy',
 'Cody, Hiram Alfred',
 'Conwell, Russell Herman',
 'Verrill, Alpheus Hyatt',
 'Foote, George William',
 'Glover, Mary Baker',
 'Giacosa, G. (Giuseppe)',
 'Branch, Stephen',
 'Beerbohm, Henry Maximilian, Sir',
 'Harris, James Thomas',
 "Baha'u'llah",
 'Stephen, Sir Leslie',
 'Froude, J. A. (James Anthony)',
 'Higginson, T. W. (Thomas Wentworth)',
 'Taylor, M. Imlay (Mary Imlay)',
 'Johnson, Owen McMahon',
 'Sheppard, William Henry Crispin',
 'Hamilton, Frederick William',
 'Marchmont, Arthur Williams',
 'Nodier, Jean Charles Emmanuel',
 'Ewald, Karl',
 'Peltonen, Vihtori',
 'Skinner, Charles Montgomery',
 'Marshall, Arthur Hammond',
 'Rette, Adolphe',
 'Lamb, Mary Ann',
 'Zschokke, Johann Heinrich Daniel',
 'Griffith-Jones, George Chetwynd',
 'Curtis, W. (William)',
 'Drake, Samuel A.',
 'Reuter, Heinrich Ludwig Christian Friedrich',
 'Charlton, Elizabeth Emily',
 'Scargill, W. Pitt (William Pitt)',
 'Kauppinen, Heikki',
 'Robertson, Margaret Murray',
 'Service, Robert William',
 'Yorick, Mr.',
 'Pennell, J. (Joseph)',
 'Sheridan, P. H. (Philip Henry)',
 'Comstock, Harriet Theresa Smith',
 'Washington, Booker Taliaferro',
 'Chambers, R. (Robert)',
 'Freitag, Gustav',
 'Barnivelt, Esdras',
 'Burnham, Clara Louise Root',
 'Peck, George Wilbur',
 'U.S.A.',
 'McDowell, Emmett',
 'McKimmey, James Earl, Jr.',
 'Campbell, Margaretta Wade',
 'Lindsay, Nicholas Vachel',
 'Robinson, Frank Malcolm',
 'Earle, Mary Alice Morse',
 'Jacobi, Carl Richard',
 'Holding, Elizabeth Sanxay',
 'Lermina, Jules Hippolyte',
 'Duer, Alice',
 'Mulford, Clarence E.',
 'Simak, Clifford Donald',
 'Oliver, George',
 'Derry Down Derry',
 'Peard, Frances M. (Frances Mary)',
 'Beers, Henry Augustin',
 'Field, Gans T.',
 'Stephens, R. N. (Robert Neilson)',
 'Frosterus, Teodor Oskar',
 'Rolt-Wheeler, Francis William',
 'Cross, Ada Cambridge',
 'Pfeiffer, Ida Reyer',
 'Mabie, Hamilton W. (Hamilton Wright)',
 'Robertson, John Mackinnon',
 'Koskenniemi, V. A. (Veikko Antero)',
 "O'Donnell, Elliot",
 'Ray, Fan',
 'Oxley, James M. (James Macdonald)',
 'Baldwin, Edward',
 'Foulis, Hugh',
 'Browne, Paul Cameron',
 'Read, Opie P.',
 'Richardson, John',
 'Ludwig, Edward William',
 'Descartes, Rene',
 'Smith, Joseph',
 'Lehtimaki, Konrad',
 'Wheeler, Post, Mrs.',
 'Austin, Mary Hunter',
 'Wilkinson, Elia',
 'Tyndal, John',
 'Lea, H. C. (Henry Charles)',
 'Pennell, E. R. (Elizabeth Robins)',
 'Blanche, August Teodor',
 'Marinetti, Filippo Tommaso',
 'Lafferty, Raphael Aloysius',
 'Johnson, W. Fletcher (Willis Fletcher)',
 'Gilbert, William Schwenck, Sir',
 'Clifton, Mark Irvin',
 'Louwerse, P.',
 'Logan, Black Jack',
 'Candolin, Arnold Elias',
 'Latham, Robert Gordon',
 'Marshall, Emma Martin',
 '劉向',
 'Mills, Enos Abijah',
 'Fry, Sheila Kaye-Smith',
 'Eliot, Thomas Stearns',
 'Valding, Victor',
 'Collins, Archie Frederick',
 'Huch, Ricarda Octavia',
 'Holyoake, G. J. (George Jacob)',
 'Tomlinson, Everett Titsworth',
 'Bodenheimer, Maxwell',
 'Leslie, Miss (Eliza)',
 'Welby, Horace',
 'Leverage, Carl Henry',
 'Gibson, C. D. (Charles Dana)',
 'Kieviet, C. Joh. (Cornelis Johannes)',
 'Lawson, Henry Archibald Hertzberg',
 'Pain, Barry Eric Odell',
 'Della Porta, Giambattista',
 'Lamballe, Marie Therese Louise de Savoie-Carignan, princesse de',
 'Farrow, George Edward',
 'Karinthy, Friedrich',
 'Macleod, Fiona',
 'Collumb, Patrick',
 'Fever, Buck',
 'Esse, James',
 'Urpia, Jaime Luciano Balmes',
 'Merilainen, Heikki',
 'Peyser, Herbert Francis',
 'Carman, William Bliss',
 'Charles, Elisabeth Rundle',
 'Driscoll, Lieutenant James R.',
 "D'Holbach, Baron",
 '孔子',
 'Wyman, Levi Parker',
 'Teichner, Albert R.',
 'Kolb, Anna Mathilde',
 'Bailey, Irene Temple',
 'Franck, Harry A.',
 'Russell, W. H. (William Howard), Sir',
 'Dunkerley, William Arthur',
 'Dryfoos, David M.',
 'Cordeaux, J.',
 'Lons, Hermann',
 'Pina, Ruy de',
 'Colton, Arthur Willis',
 'Keller, Gotfryd',
 'Rocklin, Ross Louis',
 'Karr, Jean-Alphonse',
 'Godwin, Thomas William',
 'Szep, Erno',
 'Iron, Ralph',
 'Dekker, Eduard Douwes',
 'Gyulai, Pal',
 'Larned, Josephus Nelson',
 'Sohl, Gerald Allan',
 'Josephus, Titus Flavius',
 'Sylvester, Charles H.',
 'Schopfer, Jean',
 'Whistler, C. W. (Charles Watts)',
 'Clarkson, T. (Thomas)',
 'Carpenter, Flora Leona',
 'Spearman, Frank Hamilton',
 'Fitzgerald, Francis Scott Key',
 'Mitchell, J. A. (John Ames)',
 'Blake, W. (William)',
 'Hanshew, T. W. (Thomas W.)',
 'Bain, Francis William',
 'Jordan, D. S. (David Starr)',
 'Browne, Charles Farrar',
 "M'Carthy, Justin",
 'Paris, J. A. (John Ayrton)',
 'Pain, Thomas',
 'Hume, Martin Andrew Sharp',
 'Burtis, Thomas',
 'Turner, Alice',
 'Key, Ellen Karolina Sofia',
 'Hart, A. B. (Albert Bushnell)',
 'Upward, A. (Allen)',
 'Schlemihl, Peter',
 'Sardou, V. (Victorien)',
 'Caldecott, R. (Randolph)',
 'Brown, Fred',
 'Stearns, Chas. A.',
 'Freeman, Lewis Ransome',
 'Swan-Manninen, Anni Emilia',
 'Clouston, Joseph Storer',
 'Augustine, Saint',
 'Janson, Christopher',
 'Gordon, Samuel Dickey',
 'Farmer, Philip Jose',
 'Figuier, Guillaume-Louis',
 'Stewart, J. L. (Jane L.)',
 'Wyss, J. D. (Johann David)',
 'Iisalo, Osmo',
 'Bailey, Liberty Hyde',
 'Frost, Robert Lee',
 'Wallace, Lewis',
 'Von Schmid, Christoph',
 'Davis, W. S. (William Stearns)',
 'Allen, Captain Quincy',
 'Zuccari, Anna Radius',
 'Greville, Charles Cavendish Fulke',
 'Cassels, Walter R.',
 'Beresford, John Davys',
 'Valois, Marguerite de',
 'Hopkins, William J.',
 'Ferris, George Titus',
 'Parloa, Miss (Maria)',
 'Wheatley, H. B. (Henry Benjamin)',
 'Beard, Mary Caroline',
 'Robespierre, Maximilien Marie Isidore de',
 'Van Dyne, Edith',
 'Elmendorf, Dwight',
 'Chatterton, Edward Keble',
 'Beard, Adelia Belle',
 'Rockwell, Roy',
 'Finlay, Roger Thompson',
 'Finck, Henry Theophilus',
 'Emerson, Willis G. (Willis George)',
 'Ewart, Ernest Andrew',
 'Giacomo, Salvatore di',
 'Boyesen, Hjalmar H.',
 'Fillmore, Parker H. (Parker Hoysted)',
 'Graydon, W. Murray (William Murray)',
 'Emlekyl',
 'Finberg, Alexander Joseph',
 'Knight, Edward Frederick',
 'Wilkins, William Henry',
 'Bogue, Lilian Lida Bell',
 'Weinbaum, Stanley Grauman',
 'Trent, A. G.',
 'McConnell, James Vernon',
 '韓嬰',
 'Coblentz, Stanton Arthur',
 'Stedman, Jean-Gabriel',
 'Runa',
 'College, Trinity',
 '天花藏主人',
 'Lefèvre, Edwin',
 'Talmage, James Edward',
 'Marks, Jeanette Augustus',
 'Leech, J. (John)',
 'Sanborn, Katherine Abbott',
 'Talbot, Frederick A.',
 'Mackaye, Percy',
 'Rosendal, Magnus',
 'Harker, Lizzie Allen',
 'Congrove, Mr. (William)',
 'Connolly, James Brendan',
 'Sapper, Agnes Brater',
 'Lamburn, Richmal Crompton',
 'Tyerman, Luke',
 'Gould, Nathaniel',
 'Scully, William Charles',
 'Fortescue, John William, Sir',
 'Hill, Carolyn Sherwin Bailey',
 'Fraser, W. A. (William Alexander)',
 'Society, Pennsylvania Prison',
 'Slick, Sam',
 'Keith, Marian',
 'Brooks, Henry Mason',
 'Harding, Arthur Robert',
 'Stillwell, Laura Jean Libbey',
 'Passos, John Dos',
 'Gibson, W. W. (Wilfrid Wilson)',
 'Bunner, Henry Cuyler',
 'Hayha, Johannes',
 'Bayly, Ada Ellen',
 'Robida, A. (Albert)',
 'Craig, J. H.',
 'Powell, Ardon Van Buren',
 'Phillips, H. W. (Henry Wallace)',
 'Vorst, Marie van',
 'Archette, Guy',
 'Raleigh, Sir Walter Alexander',
 'Dalquest, Walter W. (Walter Woelber)',
 'Howe, Maud',
 'Dorsey, J. Owen (James Owen)',
 'Vale, Mark',
 'Bergman, J. A.',
 'Fennel, Erick',
 'Young, Stanley P.',
 'Curtis, Wm. E. (William Eleroy)',
 'Danielson, Fannie Hurst',
 'Oppenheim, Lassa Francis Lawrence',
 'Jones, Rufus Matthew',
 'Sternheim, William Adolf Carl',
 'Valentine, Douglas',
 'Murger, Henry',
 'Leadbeater, Charles Webster',
 'Caskoden, Edwin',
 'Wedekind, Benjamin Franklin',
 'Dougall, Lily',
 'Berkley, George',
 'Inchbald, Elizabeth Simpson',
 'Malthus, Thomas Robert',
 'Swainson, W. (William)',
 'Stewart, Alfred W. (Alfred Walter)',
 'Da Verona, Guido',
 'Vanderem, Fernand',
 'Taylor, B. L. (Bert Leston)',
 'Forbes Dennis, Phyllis',
 'Amari, M. (Michele)',
 'Gibson, William Hamilton',
 'Tavaststjerna, Karl A. (Karl August)',
 'Rose, John Holland',
 'Duncker, Maximilian Wolfgang',
 'Ahrenberg, Johan Jacob',
 'Fredericks, Arnold',
 'Dickinson, Emily Elizabeth',
 'Tomlinson, Henry Major',
 'Punchard, Constance Holme',
 'Morgan, T. H. (Thomas Hunt)',
 'Dauthendey\u200f,  Maximilian Albert\u200f',
 'Szemere, Gyorgy',
 'Syrett, Janet',
 'Keller, Helen Adams',
 'Whewell, W. (William)',
 'Overton, Grant Martin',
 'United States President (1809-1817)',
 'Crake, Augustine David',
 'Henley, W. E. (William Ernest)',
 'Merenyi, Laszlo',
 'Garlanda, Ada',
 'Grisar, Hartmannus',
 'Henham, Ernest G. (Ernest George)',
 'West, Wallace George',
 '干寶',
 'Moore, Frederick F. (Frederick Ferdinand)',
 'Somerville, Mary Fairfax',
 'Lohrman, Paul',
 'Mercer, Cecil William',
 'Adam, Paul Auguste Marie',
 "D'Israeli, I. (Isaac)",
 'Kivijarvi, Erkki',
 'Marcet, Jane Haldimand',
 'Sclater, P. L. (Philip Lutley)',
 'Bryce, Viscount',
 'Davenport, Cyril James Humphries',
 'Kahn, Otto Hermann',
 'Farrel, Joseph',
 'Dey, Frederic Van Rensselaer',
 'Whiting, Emily Lillian',
 "Anderson, J. C. O'Gorman, Mrs.",
 'Gallon, T. (Tom)',
 'Clement, Clara Erskine',
 'Harrison, Mary St. Leger Kingsley',
 'Gault, William C.',
 'Finch Kelly, Florence',
 'Addams, Laura Jane',
 'Brod, Maks',
 'Trollope, Frances Eleanor Ternan',
 'Walsh, George Ethelbert',
 'Cherbuliez, Charles Victor',
 'Phillipps-Wolley, C.',
 'Braden, James Andrew',
 'Drake, Jane Ludlow',
 'Ball, Robert Stawell, Sir',
 'Beddington, Ada Esther',
 'Broster, Dorothy Kathleen',
 'Chenevix, Richard',
 'Conway, M. D. (Moncure Daniel)',
 'Kilmer, Alfred Joyce',
 'Racine, Jean Baptiste',
 'Hay, John Milton',
 'Ingram, Eleanor Marie',
 'Linnaeus, Carolus',
 'Leonard, Mary F.',
 'Bracebridge, Samuel',
 'Ingraham, Joseph Holt',
 'Magnay, Sir William',
 'Simonds, William',
 'Albertazzi',
 'Hedrick, Ulysses Prentiss',
 'Quilp, Jocelyn',
 'Dobson, Henry Austin',
 'Ganghofer, Ludwig Albert',
 'Caffin, Charles Henry',
 'Lanzi, Luigi Antonio',
 'Ady, Andrew',
 'Krehbiel, H. E. (Henry Edward)',
 'Rohlfs, Friedrich Gerhard',
 'McGuire, John Joseph',
 'Hunt, James Henry Leigh',
 'Verlaine, Paul Marie',
 'Renard, Pierre Jules',
 'Coffin, Charles C. (Charles Carleton)',
 'Bartlett, F. O. (Frederick Orin)',
 'Trumbull, Henry Clay',
 'Alcott, William Andrus',
 'Liszt, F. (Franz)',
 'Waugh, Alexander Raban',
 'Finnemore, J. (John)',
 'Morgan, Augustus de',
 'Watts, I. (Isaac)',
 'Degre, Alajos',
 'Mackenzie, Donald Alexander',
 'Strachey, Giles Lytton',
 'Dalrymple, C. Leona',
 'Grenfell, Wilfred T.',
 'Orcutt, Wm. Dana (William Dana)',
 'Stead, Robert James Campbell',
 'Putnam, Geo. Haven',
 'Spears, John R.',
 'Strong, Harrington',
 'Dodge, M. E. (Mary Elizabeth)',
 'Gubernatis, Angelo de, conte',
 'Murray, William Henry Harrison',
 'Dudley, Albertus True',
 'Cameron, V. L. (Verney Lovett)',
 'Wertenbaker, Thomas J.',
 'Chenoweth, Alice',
 'Ernst, Paul Frederick',
 'Murrey, Thomas Jefferson',
 'Trollope, T. Adolphus (Thomas Adolphus)',
 'Troward, Thomas',
 'Institute of Home Economics (U.S.). Human Nutrition Research Division',
 'Bupp, Walter',
 'Buonarroti, Michelangelo',
 'Blaikie, W. G. (William Garden)',
 'Liljencrantz, Ottilie Adelina',
 'Warneford, Lieutenant',
 'Burgon, J. W. (John William)',
 'Brewer, E. Cobham (Ebenezer Cobham)',
 'Lang, Jeanie',
 'Jacobsen, Jens Peter',
 'Dodds, Marcus',
 'Weston, Jessie Laidlay',
 'Smith, Harriet Lummis',
 'Newell, P. S. (Peter S.)',
 'Jeans, Thomas Tendron',
 'Carington, Hereward',
 'Bloy, Leon',
 'Blodgett, Levi',
 'Bruce, Henry Addington Bayley',
 'Kobbe, Gustav',
 'Engstrom, Albert',
 'Broun, Heywood Campbell',
 'Bourke, John G. (John Gregory)',
 'Bourinot, J. G. (John George)',
 'Lippmann, Julie Mathilde',
 'Campe, J. H. (Joachim Heinrich)',
 'Causey, James Oliver, Jr.',
 'Kobor, Tamas',
 'Morris, J. E. (Joseph Ernest)',
 'Verrill Mighels, Philip',
 'Jerrold, Walter Copeland',
 'Erdelyi, Janos',
 'Lemonnier, Antoine Louis Camille',
 'Brown, Giorgio Rossi',
 'Brown, Ruth Alberta',
 'Ericsson, Volter',
 'Ernst, Otto',
 'Jeunesse, Ernest La',
 'Childers, Robert Erskine',
 'Church, Richard William',
 'Upton, George Putnam',
 'Kull, George',
 'Butler, Josephine E.',
 'Neihardt, John Gneisenau',
 'Irwin, William Henry',
 'Smith, Frank Berkeley',
 'Bryant, W. C. (William Cullen)',
 'Korinek, Charles J.',
 'Livius, Titus',
 'Dilling, L.',
 'Morley, Margaret W.',
 'Greinz, Rudolf Heinrich',
 'New York detective',
 'Gilson, Charles James Louis',
 'Cecil, John',
 'Calvin, John',
 'Boethius, Anicius Manlius Severinus',
 'Mortimer, Mrs. Favell Lee (Bevan)',
 'Cimochowski, Albert Antoine',
 'Eddington, A. S. (Arthur Stanley), Sir',
 'Bourne, Randolph S.',
 'Brewster, David, Sir',